### ISSUE TITLE
Bug in Transaction ID?

### ISSUE THREAD

**Issue by 80sinteractive** [paylike/plugin-magento-1.9#2]
Hello,

I cant seem to "capture" a transaction. Even if I set the transaction id manually.

In magento this seems empty: 

input type="text" id="transaction-id" name="payment[paylike_transaction_id]"

So even If i hardcode this value to 1234 and then do this: 

curl -v -u ":XXXXXXXXXXXX" --data "amount=1600&currency=EUR" https://api.paylike.io/transactions/1234/captures

It returns 404 Transaction not found.

My best guess is that the transaction is not generated correctly, hence it will not be able to get the the transaction information when trying to capture it.

Kind regards, 

Daniel

**Comment by tjconcept** [comment]
Hi @80sinteractive 

I will ask the author of the plugin, @anil90.

> So even If i hardcode this value to 1234 and then do this:

Which value are you referring to?

Have you been able to verify that the original authorisation is visible in your dashboard after the purchase from the client side?

**Comment by 80sinteractive** [comment]
I have updated my comment to show the input field.
The input field in the checkout (Which holds the transaction-id) looks empty.

This also seemed empty: 

Paymentmethod.php:25-28
```
$payment->setTransactionId($payment->getPaylikeTransactionId());
// my code
echo $payment->getPaylikeTransactionId()"; // returns nothing
die();
```

**Comment by tjconcept** [comment]
Okay. Sounds like there are actually two problems:

1. The transaction ID returned from the Paylike popup does not get in the input field.

  Could you have a look in the dev console to see if any JS errors could prevent this from happening?

2. A payment is being accepted although no transaction ID is sent

  This one puzzles me as these lines should throw if that's the case: https://github.com/paylike/plugin-magento-1.9/blob/master/app/code/community/Paylike/Paymentmethod/Model/Paymentmethod.php#L22-L39

**Comment by 80sinteractive** [comment]
Got it: 
Paylike is not defined(anonymous function) @ (index):764

Looks like you forgot to include some JS libary in the plugin? @anil90

**Comment by tjconcept** [comment]
Hehe, that is for sure be a problem. Thanks!

Looks like our SDK (https://sdk.paylike.io/3.js) wasn't loaded at all. Any clues to why?

Still my point (2) should be addressed as well. Could you try debugging why it doesn't reach (and throw) from the authorisation method?
